// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6JwqX46oCVu7GKLdibcdxdNFVtN_MSw',
    appId: '1:393403889490:web:a12f7a7903a49d20d1ec8b',
    messagingSenderId: '393403889490',
    projectId: 'ecg-app-base',
    authDomain: 'ecg-app-base.firebaseapp.com',
    storageBucket: 'ecg-app-base.firebasestorage.app',
    measurementId: 'G-N1M0CFRD82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOd7x-ElHrjjRxPlYXIT1JBiUkyR02klQ',
    appId: '1:393403889490:android:ebaf95d4c305d4aad1ec8b',
    messagingSenderId: '393403889490',
    projectId: 'ecg-app-base',
    storageBucket: 'ecg-app-base.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2S4RaYC-7n83XQU_waYAl2WQjZYoyUmg',
    appId: '1:393403889490:ios:2012b43a1926b9bed1ec8b',
    messagingSenderId: '393403889490',
    projectId: 'ecg-app-base',
    storageBucket: 'ecg-app-base.firebasestorage.app',
    iosBundleId: 'com.example.ecgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2S4RaYC-7n83XQU_waYAl2WQjZYoyUmg',
    appId: '1:393403889490:ios:2012b43a1926b9bed1ec8b',
    messagingSenderId: '393403889490',
    projectId: 'ecg-app-base',
    storageBucket: 'ecg-app-base.firebasestorage.app',
    iosBundleId: 'com.example.ecgApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm6JwqX46oCVu7GKLdibcdxdNFVtN_MSw',
    appId: '1:393403889490:web:a7b0000932d94858d1ec8b',
    messagingSenderId: '393403889490',
    projectId: 'ecg-app-base',
    authDomain: 'ecg-app-base.firebaseapp.com',
    storageBucket: 'ecg-app-base.firebasestorage.app',
    measurementId: 'G-FMTWC1K87W',
  );
}
